import { useState, type FormEvent } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import { createCourseWithFile } from '../api/client'

interface CreateCourseModalProps { projectId: number; isOpen: boolean; onClose: () => void }

export function CreateCourseModal({ projectId, isOpen, onClose }: CreateCourseModalProps) {
  const [name, setName] = useState(''); const [file, setFile] = useState<File | null>(null); const queryClient = useQueryClient()
  const uploadMutation = useMutation({ mutationFn: () => { if (!file) throw new Error('Select a syllabus file first.'); return createCourseWithFile(projectId, name.trim(), file) }, onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['projects', String(projectId), 'courses'] }), queryClient.invalidateQueries({ queryKey: ['courses', projectId] })]); toast.success('Course created and curriculum extracted!'); setName(''); setFile(null); onClose() }, onError: () => toast.error('Failed to create course') })
  if (!isOpen) return null
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (name.trim() && file) uploadMutation.mutate() }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-labelledby="create-course-title"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl border border-zinc-800 bg-zinc-900 p-6 shadow-2xl shadow-black/50"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">New course</p><h2 id="create-course-title" className="mt-2 text-xl font-semibold text-zinc-100">Upload a syllabus</h2></div><button type="button" onClick={onClose} className="rounded-lg px-2 py-1 text-zinc-500 transition hover:bg-zinc-800 hover:text-zinc-100" aria-label="Close">×</button></div><label className="mt-6 block text-sm font-medium text-zinc-300" htmlFor="course-name">Course Name</label><input id="course-name" required value={name} onChange={(event) => setName(event.target.value)} placeholder="Intro to Biology 101" className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm text-zinc-100 outline-none placeholder:text-zinc-600 focus:border-cyan-500" /><label className="mt-5 block text-sm font-medium text-zinc-300" htmlFor="syllabus-file">Upload Syllabus</label><input id="syllabus-file" required type="file" accept=".pdf,.txt,.md,application/pdf,text/plain,text/markdown" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="mt-2 block w-full cursor-pointer rounded-lg border border-dashed border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm text-zinc-400 file:mr-4 file:rounded-md file:border-0 file:bg-zinc-800 file:px-3 file:py-1.5 file:text-sm file:font-semibold file:text-zinc-200 hover:border-zinc-600" /><p className="mt-2 text-xs text-zinc-500">PDF, TXT, or Markdown. Live extraction safely falls back to the demo curriculum if unavailable.</p>{uploadMutation.isPending && <div className="mt-5 flex items-center gap-2 text-sm text-cyan-300"><span className="h-4 w-4 animate-spin rounded-full border-2 border-cyan-300 border-t-transparent" />Extracting curriculum...</div>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} disabled={uploadMutation.isPending} className="rounded-lg px-4 py-2 text-sm font-semibold text-zinc-400 transition hover:bg-zinc-800 hover:text-zinc-100">Cancel</button><button type="submit" disabled={!name.trim() || !file || uploadMutation.isPending} className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-semibold text-zinc-950 transition hover:bg-cyan-400 disabled:cursor-not-allowed disabled:opacity-50">{uploadMutation.isPending ? 'Creating...' : 'Create & Extract'}</button></div></form></div>
}
