import { useContext } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { NavLink, Outlet, useParams } from 'react-router-dom'
import { toast, Toaster } from 'sonner'
import { AppContext } from '../App'
import { fetchCourse, fetchProjects, type Course } from '../api/client'

interface LayoutProps { isDemoMode: boolean }
const navigation = [{ label: 'Overview', tab: 'overview' }, { label: 'Curriculum', tab: 'curriculum' }, { label: 'Assessments', tab: 'assessments' }, { label: 'Learning Debugger', tab: 'debugger' }, { label: 'Files', tab: 'files' }, { label: 'Changes', tab: 'changes' }, { label: 'History', tab: 'history' }, { label: 'Settings', tab: 'settings' }]

export function Layout({ isDemoMode }: LayoutProps) {
  const { projectId, courseId } = useParams(); const queryClient = useQueryClient(); const appContext = useContext(AppContext)
  const validCourseId = Boolean(courseId && Number.isInteger(Number(courseId)) && Number(courseId) > 0)
  const courseQuery = useQuery({ queryKey: ['courses', courseId, 'graph'], queryFn: () => fetchCourse(Number(courseId)), enabled: validCourseId }); const projectsQuery = useQuery({ queryKey: ['projects'], queryFn: fetchProjects })
  const projectName = projectsQuery.data?.find((project) => project.id === Number(projectId))?.name ?? `Project #${projectId}`; const courseName = courseQuery.data?.title ?? `Course #${courseId}`; const workspacePath = `/projects/${projectId}/courses/${courseId}`
  const exportCurriculum = () => { const graph = queryClient.getQueryData<Course>(['projects', projectId, 'graph']) ?? queryClient.getQueryData<Course>(['courses', courseId, 'graph']); if (!graph) { toast.info('Load the curriculum graph before exporting.'); return }; const markdown = ['# Curriculum Export', '', `## ${graph.title}`, graph.description ?? '', '', ...graph.modules.flatMap((module) => [`## ${module.title}`, module.description ?? '', ...module.lessons.map((lesson) => `- ${lesson.title}`), ...module.learning_outcomes.map((outcome) => `- 🎯 ${outcome.statement}`), ''])].join('\n'); const url = URL.createObjectURL(new Blob([markdown], { type: 'text/markdown;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'curriculum_export.md'; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); localStorage.setItem('curriculumos_exported', 'true'); window.dispatchEvent(new Event('curriculumos-progress')); toast.success('Exported curriculum.md') }
  return <div className="flex h-screen overflow-hidden bg-zinc-950 text-zinc-100"><Toaster theme="dark" position="top-right" richColors closeButton /><aside className="flex w-64 shrink-0 flex-col border-r border-zinc-800 bg-zinc-900/70 px-3 py-5"><NavLink to={`/projects/${projectId}`} className="px-3 pb-8"><p className="text-sm font-semibold tracking-tight text-zinc-100">CurriculumOS</p><p className="mt-1 text-xs text-zinc-500">Course workspace</p></NavLink><nav className="space-y-1" aria-label="Course navigation">{navigation.map((item) => <NavLink key={item.tab} to={`${workspacePath}/${item.tab}`} className={({ isActive }) => `flex items-center rounded-lg px-3 py-2 text-sm font-medium transition-colors ${isActive ? 'bg-zinc-800 text-zinc-100 shadow-sm' : 'text-zinc-400 hover:bg-zinc-800/60 hover:text-zinc-100'}`}>{item.label}</NavLink>)}</nav><div className="mt-auto border-t border-zinc-800 px-3 pt-4 text-xs text-zinc-500">Project #{projectId} <span className="px-1">•</span> Course #{courseId}</div></aside><div className="flex min-w-0 flex-1 flex-col"><header className="flex h-16 shrink-0 items-center justify-between border-b border-zinc-800 px-6"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-zinc-500">Projects <span className="px-1">›</span> {projectName}</p><p className="mt-0.5 text-sm font-medium text-zinc-200">{courseName}</p></div><div className="flex items-center gap-3"><button type="button" onClick={exportCurriculum} className="rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-1.5 text-xs font-semibold text-zinc-300 transition duration-200 ease-out hover:scale-[1.02] hover:border-zinc-600 hover:text-zinc-100">Export</button><button type="button" onClick={() => appContext?.setIsJudgeMode(!appContext.isJudgeMode)} className={`rounded-lg border px-3 py-1.5 text-xs font-semibold transition ${appContext?.isJudgeMode ? 'border-cyan-500/60 bg-cyan-500/10 text-cyan-200' : 'border-zinc-700 bg-zinc-900 text-zinc-400 hover:text-zinc-100'}`}>Judge Mode 👁️</button><span className="flex items-center gap-2 text-xs text-zinc-400"><span className={`h-2 w-2 rounded-full ${isDemoMode ? 'bg-amber-400' : 'bg-emerald-400'}`} />{isDemoMode ? 'Demo Mode' : 'Live AI'}</span><span className="flex h-8 w-8 items-center justify-center rounded-full bg-zinc-800 text-xs font-semibold text-zinc-300">U</span></div></header>{isDemoMode && <div className="border-b border-amber-500/20 bg-amber-500/5 px-6 py-2 text-xs text-amber-200">Running in Interactive Demo Mode. Data is pre-computed to showcase the workflow.</div>}<main className="min-h-0 min-w-0 flex-1 overflow-auto"><Outlet /></main></div></div>
}
