import { useMutation } from '@tanstack/react-query'
import { useNavigate, useParams } from 'react-router-dom'
import { toast } from 'sonner'
import { apiClient } from '../api/client'

interface Diagnosis { root_cause: string; recommendation: string; affected_module: string }

export function DebuggerTab() {
  const { projectId, courseId } = useParams(); const navigate = useNavigate()
  const diagnosisMutation = useMutation({ mutationFn: async () => { const { data } = await apiClient.post<Diagnosis>(`/projects/${projectId}/debugger/diagnose`); return data }, onSuccess: () => toast.success('AI diagnosis ready'), onError: () => toast.error('Unable to diagnose curriculum performance') })
  const diagnosis = diagnosisMutation.data
  const generatePr = () => { if (!diagnosis) return; navigate(`/projects/${projectId}/courses/${courseId}/curriculum`, { state: { prompt: diagnosis.recommendation } }) }
  return <section className="mx-auto w-full max-w-5xl p-6 sm:p-10"><div className="border-b border-zinc-800 pb-7"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">Learning Debugger</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-zinc-100">Class performance</h1><p className="mt-2 text-sm text-zinc-400">Find curriculum dependencies that are creating learning friction.</p></div><div className="mt-8 rounded-2xl border border-amber-500/30 bg-amber-500/5 p-6 shadow-xl shadow-black/10"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-300">Performance alert</p><h2 className="mt-3 text-xl font-semibold text-zinc-100">⚠️ 78% of students failed Quiz 3: Recursive Tree Traversal</h2><p className="mt-2 text-sm leading-6 text-zinc-400">The failure concentration suggests a prerequisite gap rather than an isolated assessment issue.</p><button type="button" onClick={() => diagnosisMutation.mutate()} disabled={diagnosisMutation.isPending} className="mt-6 rounded-lg bg-cyan-500 px-4 py-2.5 text-sm font-semibold text-zinc-950 transition hover:bg-cyan-400 disabled:cursor-not-allowed disabled:opacity-50">{diagnosisMutation.isPending ? 'Diagnosing...' : 'Ask AI to Diagnose'}</button></div>{diagnosis && <article className="mt-6 rounded-2xl border border-cyan-500/30 bg-cyan-500/5 p-6 shadow-xl shadow-cyan-950/20"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">AI Insight</p><div className="mt-5 grid gap-5 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-zinc-500">Root cause</p><p className="mt-2 text-base font-medium text-zinc-100">{diagnosis.root_cause}</p></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-zinc-500">Affected module</p><p className="mt-2 text-base font-medium text-zinc-100">{diagnosis.affected_module}</p></div></div><div className="mt-6 rounded-xl border border-zinc-700 bg-zinc-950/70 p-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-violet-300">Recommendation</p><p className="mt-2 text-lg font-semibold text-zinc-100">{diagnosis.recommendation}</p></div><button type="button" onClick={generatePr} className="mt-6 rounded-lg bg-violet-500 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-violet-400">Generate Curriculum PR</button></article>}</section>
}
