"""Add is_archived to projects, courses, assessments

Revision ID: 04891b25a520
Revises: b6d42e7f9a10
Create Date: 2026-07-19 23:01:27.872460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04891b25a520'
down_revision: Union[str, Sequence[str], None] = 'b6d42e7f9a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
